### ISSUE TITLE
Todo App 기능 작업

### ISSUE THREAD

**Issue by moonozz** [moonozz/darkmode-todo#1]
### 기능 설명
Todo data json-server 연결

### 구현하기 위해 해야할 일
1. [x] data.json 만들기
2. [x] App 렌더링 시 data 불러오기
3. [x] CRUD 맞게 fetch 작성하기

### 예상 작업 시간
1d
